specVersion: 0.0.2
schema:
  file: ./protocols/marketxyz/schema.graphql
dataSources:
  - kind: ethereum/contract
    name: PoolDirectory
    network: {{ network }}
    source:
      address: "{{ poolDirectoryAddress }}"
      abi: PoolDirectory
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Market
      abis:
        - name: PoolDirectory
          file: ./abis/marketxyz/PoolDirectory.json
        - name: Comptroller
          file: ./abis/Comptroller.json
      eventHandlers:
        - event: PoolRegistered(uint256,(string,address,address,uint256,uint256))
          handler: handlePoolRegistered
      file: ./protocols/marketxyz/src/mappings.ts
templates:
  - name: Comptroller
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: MarketComptroller
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./protocols/marketxyz/src/mappings.ts
      entities:
        - LendingProtocol
        - Market
        - Token
      abis:
        - name: MarketComptroller
          file: ./abis/marketxyz/MarketComptroller.json
        - name: CToken
          file: ./abis/marketxyz/CToken.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: PriceOracle
          file: ./abis/PriceOracle.json
      eventHandlers:
        - event: MarketListed(address)
          handler: handleMarketListed
        - event: NewCollateralFactor(address,uint256,uint256)
          handler: handleNewCollateralFactor
        - event: NewLiquidationIncentive(uint256,uint256)
          handler: handleNewLiquidationIncentive
        - event: NewPriceOracle(address,address)
          handler: handleNewPriceOracle
        - event: ActionPaused(address,string,bool)
          handler: handleActionPaused
        - event: WhitelistEnforcementChanged(bool)
          handler: handleWhitelistEnforcementChanged
  - name: CToken
    kind: ethereum/contract
    network: {{ network }}
    source:
      abi: CToken
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./protocols/marketxyz/src/mappings.ts
      entities:
        - Event
        - Market
        - UsageMetricsDailySnapshot
        - FinancialsDailySnapshot
        - MarketDailySnapshot
      abis:
        - name: MarketComptroller
          file: ./abis/marketxyz/MarketComptroller.json
        - name: CToken
          file: ./abis/marketxyz/CToken.json
        - name: ERC20
          file: ./abis/ERC20.json
        ###########################################
        ############## Price Oracle ###############
        ###########################################
        - name: PriceOracle
          file: ./abis/PriceOracle.json
        - name: MasterPriceOracle
          file: ./abis/marketxyz/MasterPriceOracle.json
        # ERC20
        - name: _ERC20
          file: ./abis/prices/ERC20.json
      eventHandlers:
        - event: Mint(address,uint256,uint256)
          handler: handleMint
        - event: Redeem(address,uint256,uint256)
          handler: handleRedeem
        - event: Borrow(address,uint256,uint256,uint256)
          handler: handleBorrow
        - event: RepayBorrow(address,address,uint256,uint256,uint256)
          handler: handleRepayBorrow
        - event: LiquidateBorrow(address,address,uint256,address,uint256)
          handler: handleLiquidateBorrow
        - event: AccrueInterest(uint256,uint256,uint256,uint256)
          handler: handleAccrueInterest
        - event: NewReserveFactor(uint256,uint256)
          handler: handleNewReserveFactor
        - event: NewFuseFee(uint256,uint256)
          handler: handleNewFuseFee
        - event: NewAdminFee(uint256,uint256)
          handler: handleNewAdminFee
